### PR TITLE
Tweak topkg post.

### PR DESCRIPTION
**Pull request by dbuenzli**
According to the comments I made in https://github.com/mirage/mirage-www/issues/513#issuecomment-282255437

### CODE REVIEW

**Comment by GemmaG** [comment]
Tweaked as per comments from @dbuenzli - Thanks!

**Comment by amirmc** [comment]
I'm just curious, is there a reason  why this couldn't be merged?  The edit in https://github.com/ocamllabs/ocamllabs-www/commit/079369390da5ab2f2d9d94e4e0ebfaf091dca8da also seems to remove the post metadata at the top.

**Comment by amirmc** [comment]
And now the URL is changed.  It was http://ocamllabs.io/projects/2017/02/23/topkg.html but is now http://ocamllabs.io/2017/02/23/topkg.html.  Is this deliberate?  If so, we'll need to update the link from the section in the MirageOS release post ([ref](https://mirage.io/blog/announcing-mirage-30-release#BuildSystemShift))

**Comment by GemmaG** [comment]
Ah I messed something up in an interim edit - URL is http://ocamllabs.io/projects/2017/02/23/topkg.html as per original post and link from MirageOS post.

Aaaand I didn't know how to merge :P Thanks @amirmc!

**Pull request closed without merging**
